# Generated by Django 4.2.7 on 2024-01-14 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                   CREATE INDEX idx_first_last_name_pattern_ops
                   ON users_user (first_name varchar_pattern_ops, last_name varchar_pattern_ops);
                   """,
            reverse_sql="DROP INDEX idx_first_last_name_pattern_ops;"
        ),
    ]
