services:
  db_master:
    build:
      context: ./postgres
      dockerfile: master.Dockerfile
    container_name: 9999_db_master
    restart: always
    volumes:
      - 9999_postgres_master:/var/lib/postgresql/data

  db_replica_1:
    build:
      context: ./postgres
      dockerfile: replica.Dockerfile
    container_name: 9999_db_replica_1
    restart: always
    depends_on:
      - db_master
    volumes:
      - 9999_postgres_replica_1:/var/lib/postgresql/data
    environment:
      - PGPASSWORD=replicator_password

  db_replica_2:
    build:
      context: ./postgres
      dockerfile: replica.Dockerfile
    container_name: 9999_db_replica_2
    restart: always
    depends_on:
      - db_master
    volumes:
      - 9999_postgres_replica_2:/var/lib/postgresql/data
    environment:
      - PGPASSWORD=replicator_password
  
  server:
    build: .
    container_name: 9999_server
    platform: linux/amd64
    command: runserver
    restart: always
    volumes:
      - ./:/app/
    ports:
      - "8001:8000"
    depends_on:
      - db_master
      - db_replica_1
      - db_replica_2

  loadtest:
    build: .
    container_name: 9999_loadtest
    command: loadtest
    restart: always
    volumes:
      - ./locustfile.py:/app/locustfile.py
    ports:
      - "8089:8089"
    depends_on:
      - server

volumes:
  9999_postgres_master:
  9999_postgres_replica_1:
  9999_postgres_replica_2:
