version: '3.7'

services:
  db:
    image: postgres:16.1
    container_name: django_social_db
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build: .
    image: django_social_server
    container_name: django_social_server
    command: runserver
    restart: always
    volumes:
      - ./:/app/
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
