version: '3.7'

services:
  db:
    image: postgres:16.1
    container_name: django_social_db
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build: .
    image: django_social_server
    container_name: django_social_server
    platform: linux/amd64
    command: runserver
    restart: always
    volumes:
      - ./:/app/
    ports:
      - "8001:8000"
    depends_on:
      - db

  loadtest:
    image: django_social_server
    container_name: django_social_loadtest
    command: loadtest
    restart: always
    volumes:
      - ./locustfile.py:/app/locustfile.py
    ports:
      - "8089:8089"
    depends_on:
      - server

volumes:
  postgres_data:
